    // Tableau contenant des citations
    const quotes = [
      "La vie est une fleur dont l'amour est le miel. - Victor Hugo",
      "La seule façon de faire du bon travail est d'aimer ce que vous faites. - Steve Jobs",
      "Le succès, c'est tomber sept fois et se relever huit. - Proverbe japonais",
      "La vie n'est pas d'attendre que les orages passent, c'est d'apprendre à danser sous la pluie. - Sénèque",
      "Le bonheur est parfois caché dans l'inconnu. - Victor Hugo",
      "La vie devient une aventure quand on la reconnaît comme une chance de grandir. - Mary Tyler Moore",
      "La vie n'est pas d'attendre que les tempêtes passent, c'est d'apprendre à danser sous la pluie. - Vivian Greene",
      "L'éducation coûte cher, mais l'ignorance coûte plus cher. - Sir Claus Moser",
      "Le bonheur est une direction, pas une destination. - Ralph Waldo Emerson",
      "La vie est un mystère à vivre, non un problème à résoudre. - Mahatma Gandhi",
      "La vie est ce qui se passe pendant que vous êtes occupé à faire d'autres plans. - Allen Saunders",
      "Le succès c'est se relever une fois de plus que le nombre de fois où vous tombez. - Anonyme",
      "Le seul chemin vers le succès est de travailler dur, ne jamais abandonner et apprendre des échecs. - Roy T. Bennett",
      "Le seul moyen de faire du bon travail est d'aimer ce que vous faites. - Steve Jobs",
      "Le succès consiste à aller d'échec en échec sans perdre son enthousiasme. - Winston Churchill",
      "Le succès est la somme de petits efforts, répétés jour après jour. - Robert Collier",
      "Le succès n'est pas la clé du bonheur. Le bonheur est la clé du succès. Si vous aimez ce que vous faites, vous réussirez. - Albert Schweitzer",
      "Le succès n'est pas la clé du bonheur. Le bonheur est la clé du succès. Si vous aimez ce que vous faites, vous réussirez. - Albert Schweitzer",
      "Un homme qui n'est pas prêt à mourir pour quelque chose ne mérite pas de vivre. - Martin Luther King Jr.",
      "Un homme qui n'a jamais fait d'erreur n'a jamais rien essayé de nouveau. - Albert Einstein",
      "Les deux jours les plus importants de votre vie sont le jour où vous êtes né et le jour où vous découvrez pourquoi. - Mark Twain",
      "Un homme qui ne sait pas pardonner empoisonne son âme. - Proverbe africain",
      "Un voyage de mille kilomètres commence toujours par un premier pas. - Lao Tzu",
      "Le succès n'est pas final, l'échec n'est pas fatal : c'est le courage de continuer qui compte. - Winston Churchill",
      "La vie est faite de choix. - Anonyme",
      "Il n'y a qu'une chose qui rend un rêve impossible à réaliser : la peur de l'échec. - Paulo Coelho",
      "Vous ne pouvez pas juger un poisson sur sa capacité à grimper à un arbre. - Albert Einstein",
      "La seule limite à nos réalisations de demain sera nos doutes d'aujourd'hui. - Franklin D. Roosevelt",
      "La seule façon de faire du bon travail est d'aimer ce que vous faites. - Steve Jobs",
      "Si vous voulez quelque chose que vous n'avez jamais eu, vous devez être prêt à faire quelque chose que vous n'avez jamais fait. - Thomas Jefferson",
      "La vie est 10% de ce qui nous arrive et 90% de la façon dont nous réagissons. - Charles R. Swindoll",
      "Le succès n'est pas la clé du bonheur. Le bonheur est la clé du succès. Si vous aimez ce que vous faites, vous réussirez. - Albert Schweitzer",
      "Seuls ceux qui prennent le risque d'aller trop loin peuvent découvrir jusqu'où on peut aller. - T.S. Eliot",
      "Le succès n'est pas final, l'échec n'est pas fatal : c'est le courage de continuer qui compte. - Winston Churchill",
      "La vie est comme une bicyclette, il faut avancer pour ne pas perdre l'équilibre. - Albert Einstein",
      "Le succès, c'est tomber sept fois et se relever huit. - Proverbe japonais",
      "La seule façon de faire du bon travail est d'aimer ce que vous faites. - Steve Jobs",
      "La seule façon de faire du bon travail est d'aimer ce que vous faites. - Steve Jobs",
      "Le succès c'est se relever une fois de plus que le nombre de fois où vous tombez. - Anonyme",
      "La vie n'est pas d'attendre que les orages passent, c'est d'apprendre à danser sous la pluie. - Sénèque",
      "La vie est ce qui se passe pendant que vous êtes occupé à faire d'autres plans. - Allen Saunders",
      "La vie est un mystère à vivre, non un problème à résoudre. - Mahatma Gandhi",
      "Le succès c'est se relever une fois de plus que le nombre de fois où vous tombez. - Anonyme",
      "Le seul moyen de faire du bon travail est d'aimer ce que vous faites. - Steve Jobs",
      "Le seul chemin vers le succès est de travailler dur, ne jamais abandonner et apprendre des échecs. - Roy T. Bennett",
      "Le succès c'est se relever une fois de plus que le nombre de fois où vous tombez. - Anonyme",
      "La vie n'est pas d'attendre que les orages passent, c'est d'apprendre à danser sous la pluie. - Sénèque",
      "La seule façon de faire du bon travail est d'aimer ce que vous faites. - Steve Jobs",
      "Le succès c'est se relever une fois de plus que le nombre de fois où vous tombez. - Anonyme",
      "La seule façon de faire du bon travail est d'aimer ce que vous faites. - Steve Jobs",
      "La vie est ce qui se passe pendant que vous êtes occupé à faire d'autres plans. - Allen Saunders",
      "Le succès c'est se relever une fois de plus que le nombre de fois où vous tombez. - Anonyme",
      "La vie est un mystère à vivre, non un problème à résoudre. - Mahatma Gandhi",
      "La vie est un mystère à vivre, non un problème à résoudre. - Mahatma Gandhi",
      "La seule façon de faire du bon travail est d'aimer ce que vous faites. - Steve Jobs",
      "Le succès, c'est tomber sept fois et se relever huit. - Proverbe japonais",
      "Le seul moyen de faire du bon travail est d'aimer ce que vous faites. - Steve Jobs",
      "La vie est ce qui se passe pendant que vous êtes occupé à faire d'autres plans. - Allen Saunders",
      "La vie est un mystère à vivre, non un problème à résoudre. - Mahatma Gandhi",
      "Le succès n'est pas la clé du bonheur. Le bonheur est la clé du succès. Si vous aimez ce que vous faites, vous réussirez. - Albert Schweitzer",
      "Un homme qui n'a jamais fait d'erreur n'a jamais rien essayé de nouveau. - Albert Einstein",
      "Les deux jours les plus importants de votre vie sont le jour où vous êtes né et le jour où vous découvrez pourquoi. - Mark Twain",
      "La seule limite à nos réalisations de demain sera nos doutes d'aujourd'hui. - Franklin D. Roosevelt",
      "Si vous voulez quelque chose que vous n'avez jamais eu, vous devez être prêt à faire quelque chose que vous n'avez jamais fait. - Thomas Jefferson",
      "La vie est 10% de ce qui nous arrive et 90% de la façon dont nous réagissons. - Charles R. Swindoll",
      "Un voyage de mille kilomètres commence toujours par un premier pas. - Lao Tzu",
      "La vie est comme une bicyclette, il faut avancer pour ne pas perdre l'équilibre. - Albert Einstein",
      "Le succès, c'est tomber sept fois et se relever huit. - Proverbe japonais",
      "Le seul chemin vers le succès est de travailler dur, ne jamais abandonner et apprendre des échecs. - Roy T. Bennett",
      "Le seul chemin vers le succès est de travailler dur, ne jamais abandonner et apprendre des échecs. - Roy T. Bennett",
      "La vie est un mystère à vivre, non un problème à résoudre. - Mahatma Gandhi",
      "Un homme qui n'a jamais fait d'erreur n'a jamais rien essayé de nouveau. - Albert Einstein",
      "Les deux jours les plus importants de votre vie sont le jour où vous êtes né et le jour où vous découvrez pourquoi. - Mark Twain",
      "La seule limite à nos réalisations de demain sera nos doutes d'aujourd'hui. - Franklin D. Roosevelt",
      "Un voyage de mille kilomètres commence toujours par un premier pas. - Lao Tzu",
      "La vie est comme une bicyclette, il faut avancer pour ne pas perdre l'équilibre. - Albert Einstein"
  ];
  
      
  
      function generateQuote() {
        // Générer un nombre aléatoire pour choisir une citation dans le tableau
        const randomNumber = Math.floor(Math.random() * quotes.length);
        
        // Afficher la citation dans la div avec l'id "quote"
        document.getElementById('quote').innerText = quotes[randomNumber];
      }

      //ahmad warren